# ====================================
# SERVIDOR
# ====================================
server.port=${SERVER_PORT:8080}
server.host=0.0.0.0

# ====================================
# CONSUL
# ====================================
consul.host=${CONSUL_HOST:localhost}
consul.port=${CONSUL_PORT:8500}

consul.service.address=${SERVICE_HOST:localhost}
consul.health.host=${SERVICE_HOST:localhost}
consul.health.path=/health/live
consul.register.delay.ms=3000

# ====================================
# DATASOURCE POSTGRESQL
# ====================================
javax.sql.DataSource.jdbc/postgres.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.jdbc/postgres.dataSource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
javax.sql.DataSource.jdbc/postgres.dataSource.user=${DB_USER:postgres}
javax.sql.DataSource.jdbc/postgres.dataSource.password=${DB_PASSWORD:postgres}

# ====================================
# FLYWAY
# ====================================
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

# ====================================
# JPA
# ====================================
jakarta.persistence.schema-generation.database.action=none
