# ====================================
# SERVIDOR
# ====================================
server.port=8030
server.host=0.0.0.0

# ====================================
# CONSUL
# ====================================
consul.host=127.0.0.1
consul.port=8500

# Estos valores ayudan si luego los quieres reutilizar en el lifecycle
consul.service.address=127.0.0.1
consul.health.host=127.0.0.1
consul.health.path=/health/live
consul.register.delay.ms=3000

# ====================================
# REST CLIENT - app-authors
# ====================================
# URL del servicio de autores
authors-api/mp-rest/url=http://localhost:8080

# Si usas Traefik, descomenta:
# authors-api/mp-rest/url=http://localhost:80/app-authors

# Configuración del cliente
authors-api/mp-rest/scope=jakarta.inject.Singleton
authors-api/mp-rest/connectTimeout=5000
authors-api/mp-rest/readTimeout=10000



# ====================================
# DATASOURCE POSTGRESQL (Helidon style)
# MISMA BASE DE DATOS QUE AUTHORS
# ====================================
javax.sql.DataSource.jdbc/postgres.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.jdbc/postgres.dataSource.url=jdbc:postgresql://localhost:5432/postgres
javax.sql.DataSource.jdbc/postgres.dataSource.user=postgres
javax.sql.DataSource.jdbc/postgres.dataSource.password=postgres

# ====================================
# FLYWAY
# ====================================
flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true

# ====================================
# JPA / ECLIPSELINK
# ====================================
jakarta.persistence.schema-generation.database.action=none

