CREATE TABLE author
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    version INTEGER,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

insert into author (name, version) values ('Gabriel Garcia Marquez', 1);
insert into author (name, version) values ('Isabel Allende', 1);
insert into author (name, version) values ('Jorge Luis Borges', 1);